version: 2.1

workflows:
  build-and-test:
    jobs:
      - build:
          context: smartfarm
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: cimg/openjdk:17.0
        auth:
          username: ${DOCKERHUB_USERNAME}
          password: ${DOCKERHUB_PASSWORD}
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - my-cache-{{ .Branch }}-{{ checksum "pom.xml" }}
      - run: mvn clean install
      - save_cache:
          paths:
            - ~/.m2
          key: my-cache-{{ .Branch }}-{{ checksum "pom.xml" }}
      - run:
          name: Build Docker Image
          command: |
            mvn docker:build
      - run:
          name: Push Docker Image
          command: |
            mvn -e docker:push