version: 2.1
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: cimg/openjdk:17.0
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - my-cache-{{ .Branch }}-{{ checksum "pom.xml" }}
      - run: mvn clean install
      - save_cache:
          paths:
            - ~/.m2
          key: my-cache-{{ .Branch }}-{{ checksum "pom.xml" }}
      - run:
          name: check dir
          command: |
            echo "${PATH//:/$'\n'}"
      - run: pwd
      - run:
          command: |
            ls
            cd src/main/docker
            ls
      - run:
          name: Build Docker Image
          command: |
            mvn docker:build
      - run:
          name: Push Docker Image
          command: |
            mvn -e docker:push
#            mvn docker:push -DdockerUser=${DOCKERHUB_USERNAME} -DdockerPassword=${DOCKERHUB_PASSWORD}
#      - run:
#          name: Push Docker Image
#          command: |
#            docker tag sensor-data-producer-service:latest thebestsmartfarm/sensor-data-producer-service:latest
#            docker push thebestsmartfarm/sensor-data-producer-service:latest