version: 2.1
jobs:
  build:
    working_directory: ~/sensor-data-producer-service/src/main/docker
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run: mvn clean install
      - run:
          name: Build Docker Image
          command: |
            docker build \
              --tag sensor-data-producer-service:latest \
              --build-arg JAR_FILE=target/sensor-data-producer-service-0.0.1-SNAPSHOT.jar \
              .
      - run:
          name: Login to Docker Registry
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Push Docker Image
          command: |
            docker tag sensor-data-producer-service:latest thebestsmartfarm/sensor-data-producer-service:latest
            docker push thebestsmartfarm/sensor-data-producer-service:latest