version: 2.1
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run: mvn clean install
      - run:
          name: check dir
          command: |
            echo "${PATH//:/$'\n'}"
      - run: pwd
      - run:
          command: |
            ls
            cd scr
            ls
      - run:
          name: Build Docker Image
          command: |
            docker build . -f ~/project/src/main/docker/Dockerfile
      - run:
          name: Login to Docker Registry
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Push Docker Image
          command: |
            docker tag sensor-data-producer-service:latest thebestsmartfarm/sensor-data-producer-service:latest
            docker push thebestsmartfarm/sensor-data-producer-service:latest