version: 2.1
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/openjdk:17-jdk-buster
    steps:
      - checkout
      - run: mvn clean install
      - run:
          name: check dir
          command: |
            ls
            cd src
            ls
      - run: cd src
      - run: ls
      - run:
          name: Build Docker Image
          command: |
            docker build . -f ~/project/src/main/docker/Dockerfile
      - run:
          name: Login to Docker Registry
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Push Docker Image
          command: |
            docker tag sensor-data-producer-service:latest thebestsmartfarm/sensor-data-producer-service:latest
            docker push thebestsmartfarm/sensor-data-producer-service:latest